### ISSUE TITLE
Tag Support

### ISSUE THREAD

**Issue by mbrown1413** [mbrown1413/vgloss#18]
Tags are referenced in URLs and APIs by their ID. Names can change, but IDs do not.

Tags can be arbitrarily nested. On the backend this is stored as a pointer from a tag to its parent. The frontend is presented with a tree structure of tags, just like the tree of folders. The filter tree on the frontend will show subtags, and also a checkbox for "(no subtag)" for selecting files that are directly tagged by that tag, and not a subtag.

When listing files, the frontend sends a list of tags to the backend to include.

Questions:
  * [X] How does the tag filtering work with subtags? Does the frontend have to list out a tag and all of its descendant subtags if it wants to filter all of them? Is there a special syntax for including a tag and all its subtags (tags=7,4+)? What about selecting a tag but not its subtags? Remember the tag filter has to be present in the URL.
    * In the future I want a different model for tag filtering, where the user can both positively and negatively select tags.

## Milestones
  * [x] Tag CRUD
    * [x] Backend API
      * [x] Basic CRUD
      * [x] Parent field
    * [x] Frontend editor
      * [x] Return tags in gallery query
      * [x] Tag data in store
      * [x] Modal showing tree
      * [x] New tag
      * [x] Delete tag
      * [x] Change tag
  * [x] Show tag filter tree
      * [x] Do we generalize existing tree component, or make a new one?
  * [x] Tag add / remove
      * [x] Return file tags in file list query
      * [x] Decide on interface (right/click, drop-down, or buttons next to tag list)
      * [x] Implement
  * [x] Filter by tag
    * [x] Decide on filter API
    * [x] Backend
    * [x] Frontend
      * [x] Tag list as URL param
      * [x] Tag list sent to file list API

  * [x] Create issue for future enhancements
    * <strike>Description field</strike> - Not sure if we need this on the roadmap right now.
    * <strike>Tag a folder - All files put in the folder are automatically assigned that tag.</strike> - Not sure if we need this on the roadmap right now.
    * <strike>Tag Icons - Custom, or some preset, such as a star, or 1-5 stars. Associated single character to put in the corner of the icon (such as 1-5 over a star icon).</strike>
    * <strike>Saving tags should be done in one atomic call for create/update/delete.</strike> - This will be done when the API is redesigned.
    * TagEditModal TODO for UI improvements
      * <strike>"Remove" button - Placement is a little weird. Consider putting a "-" button next to the "+", which is disabled if nothing is selected. This may make it too easy to accidentally press though. Undo functionality would make this better.</strike>
      * <strike>Undo functionality</strike> - Not sure we need this on the roadmap right now.
      * <strike>Deep tags structure in tree overflows to right side.</strike>
      * <strike>Parent dropdown is usable but a little weird to have indentations inside the options to show the tree structure.</strike>
      * <strike>Parent dropdown items are not sorted in the same order as the tree.</strike>
      * <strike>When a new tag is created, I would expect it's parent to default to the selected node, but that's odd since you can't de-select a tag in the interface. Maybe a newly created tag should be a sibling of the selected tag. That makes sense if you want to create a bunch of tags in the same category in a row, they will all have the same parent.</strike>
      * <strike>In the "Apply Tags" dropdown, show "half-checked" checkboxes when multiple files are selected, and only some have a given tag. (For now, tags are shown as unchecked if not all have the tag)</strike> - This will be redone when we have

**Comment by mbrown1413** [comment]
Initial implementation done, but there are definitely improvements needed before version 1.
